FROM node:18-slim AS builder

WORKDIR /next-app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /next-app

COPY --from=builder /next-app/.next ./.next
COPY --from=builder /next-app/public ./public
COPY --from=builder /next-app/package*.json ./

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]