name: pi-motor-de-busca-4-sem
services:
  mongo:
    image: mongo:latest
    networks:
      - app-network
    ports:
      - target: 27017
        published: "27017"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # Diretório com scripts de inicialização
  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    volumes:
      - ./next-app:/app   # <--- adicionado aqui  
    depends_on:
      mongo:
        condition: service_started
        required: true
    environment:
      MONGO_URI: mongodb://mongo:27017/MotorDeBusca
    networks:
      - app-network
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp

networks:
  app-network:
    name: pi-motor-de-busca-4-sem_app-network
    driver: bridge

volumes:
  mongo-data:
    name: pi-motor-de-busca-4-sem_mongo-data
