services:
  next-app:
    build:
      context: ./next-app
      dockerfile: DockerFile
    environment:
      MONGO_URI: mongodb+srv://usuario:senha@clusterlastrearimoveis.xhmcrgi.mongodb.net/
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: npm start

  # scrapers:
  #   build: ./scrapers
  #   container_name: scrapers
  #   environment:
  #     MONGO_URI: mongodb+srv://usuario:senha@clusterlastrearimoveis.xhmcrgi.mongodb.net/
  #   networks:
  #     - app-network

networks:
  app-network:
    name: pi-motor-de-busca-4-sem_app-network
    driver: bridge
