version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - target: 27017
        published: "27018"
        protocol: tcp
    networks:
      - app-network
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
      - ./next-app/scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  next-app:
    build:
      context: ./next-app
      dockerfile: DockerFile
    volumes:
      - ./next-app:/app
    depends_on:
      mongo:
        condition: service_started
        required: true
    environment:
      MONGO_URI: mongodb://root:example@mongo:27018/MotorDeBusca?authSource=admin
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    networks:
      - app-network

  scrapers:
    build: ./scrapers
    container_name: scrapers
    depends_on:
      - mongo
    volumes:
      - ./scrapers:/app
    networks:
      - app-network

networks:
  app-network:
    name: pi-motor-de-busca-4-sem_app-network
    driver: bridge

volumes:
  mongo-data:
    name: pi-motor-de-busca-4-sem_mongo-data
